//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMusicPlayer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMusicPlayer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Z001_About {
            get {
                return ResourceManager.GetString("Z001_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string Z001_AccentColor {
            get {
                return ResourceManager.GetString("Z001_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Z001_Address {
            get {
                return ResourceManager.GetString("Z001_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Z001_Album {
            get {
                return ResourceManager.GetString("Z001_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album background.
        /// </summary>
        public static string Z001_AlbumBackground {
            get {
                return ResourceManager.GetString("Z001_AlbumBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album foreground.
        /// </summary>
        public static string Z001_AlbumForeground {
            get {
                return ResourceManager.GetString("Z001_AlbumForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Z001_Albums {
            get {
                return ResourceManager.GetString("Z001_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All songs.
        /// </summary>
        public static string Z001_AllSongs {
            get {
                return ResourceManager.GetString("Z001_AllSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 Music.
        /// </summary>
        public static string Z001_AppTitle {
            get {
                return ResourceManager.GetString("Z001_AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string Z001_Artist {
            get {
                return ResourceManager.GetString("Z001_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist background.
        /// </summary>
        public static string Z001_ArtistBackground {
            get {
                return ResourceManager.GetString("Z001_ArtistBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist foreground.
        /// </summary>
        public static string Z001_ArtistForeground {
            get {
                return ResourceManager.GetString("Z001_ArtistForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black.
        /// </summary>
        public static string Z001_Black {
            get {
                return ResourceManager.GetString("Z001_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy this app.
        /// </summary>
        public static string Z001_Buy {
            get {
                return ResourceManager.GetString("Z001_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string Z001_CheckUpdate {
            get {
                return ResourceManager.GetString("Z001_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open.
        /// </summary>
        public static string Z001_ClickToOpen {
            get {
                return ResourceManager.GetString("Z001_ClickToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close lists.
        /// </summary>
        public static string Z001_CloseLists {
            get {
                return ResourceManager.GetString("Z001_CloseLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the hidden button, top left to close all lists..
        /// </summary>
        public static string Z001_CloseListsTxt {
            get {
                return ResourceManager.GetString("Z001_CloseListsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Z001_CMOpen {
            get {
                return ResourceManager.GetString("Z001_CMOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Z001_CMPlay {
            get {
                return ResourceManager.GetString("Z001_CMPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play album.
        /// </summary>
        public static string Z001_CMPlayAlbum {
            get {
                return ResourceManager.GetString("Z001_CMPlayAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play song.
        /// </summary>
        public static string Z001_CMPlaySong {
            get {
                return ResourceManager.GetString("Z001_CMPlaySong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Z001_Color {
            get {
                return ResourceManager.GetString("Z001_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color settings.
        /// </summary>
        public static string Z001_ColorSettings {
            get {
                return ResourceManager.GetString("Z001_ColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string Z001_Connecting {
            get {
                return ResourceManager.GetString("Z001_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string Z001_ConnectionFailed {
            get {
                return ResourceManager.GetString("Z001_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time out.
        /// </summary>
        public static string Z001_ConnectionTimeOut {
            get {
                return ResourceManager.GetString("Z001_ConnectionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Z001_Contact {
            get {
                return ResourceManager.GetString("Z001_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Z001_Delete {
            get {
                return ResourceManager.GetString("Z001_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete last playbacks.
        /// </summary>
        public static string Z001_DeleteLastPlaybacks {
            get {
                return ResourceManager.GetString("Z001_DeleteLastPlaybacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete list with last playbacks.
        /// </summary>
        public static string Z001_DeleteLastPlaybacksNote {
            get {
                return ResourceManager.GetString("Z001_DeleteLastPlaybacksNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design settings.
        /// </summary>
        public static string Z001_DesignSettings {
            get {
                return ResourceManager.GetString("Z001_DesignSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended informations.
        /// </summary>
        public static string Z001_ExtendedInfo {
            get {
                return ResourceManager.GetString("Z001_ExtendedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string Z001_FontSize {
            get {
                return ResourceManager.GetString("Z001_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Foreground.
        /// </summary>
        public static string Z001_ForegroundColor {
            get {
                return ResourceManager.GetString("Z001_ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking on the left arrow opens the fullscreen player..
        /// </summary>
        public static string Z001_FullscreenPlayerTxt {
            get {
                return ResourceManager.GetString("Z001_FullscreenPlayerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Z001_Genre {
            get {
                return ResourceManager.GetString("Z001_Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Z001_Genres {
            get {
                return ResourceManager.GetString("Z001_Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        public static string Z001_Hour {
            get {
                return ResourceManager.GetString("Z001_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Z001_Hours {
            get {
                return ResourceManager.GetString("Z001_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Z001_InstGeneral {
            get {
                return ResourceManager.GetString("Z001_InstGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this application, you get the fastest to your music. You can choose all your music from only two lists. In addition, the application gives you many great extensions..
        /// </summary>
        public static string Z001_InstGeneralTxt {
            get {
                return ResourceManager.GetString("Z001_InstGeneralTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list view.
        /// </summary>
        public static string Z001_InstListView {
            get {
                return ResourceManager.GetString("Z001_InstListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using list view, you can quickly reach your music. All artists are listed in the first list. If you click on the desired then opened his albums. A further click on the album displays all the songs.
        ///In the second list, playlists, genres, albums and all songs are listed..
        /// </summary>
        public static string Z001_InstListViewTxt {
            get {
                return ResourceManager.GetString("Z001_InstListViewTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Z001_InstMiscellaneous {
            get {
                return ResourceManager.GetString("Z001_InstMiscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate good this application if you like. If you have problems with this application, then please contact support! Questions and problems have lost nothing in the reviews.
        ///Thank you very much!.
        /// </summary>
        public static string Z001_InstMiscellaneousTxt {
            get {
                return ResourceManager.GetString("Z001_InstMiscellaneousTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play on.
        /// </summary>
        public static string Z001_InstPlayOn {
            get {
                return ResourceManager.GetString("Z001_InstPlayOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has a play on function. With this function, the titles will be replayed only the set time. To enable play on,  you must hold the play button for a second during playback..
        /// </summary>
        public static string Z001_InstPlayOnTxt {
            get {
                return ResourceManager.GetString("Z001_InstPlayOnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Z001_Instructions {
            get {
                return ResourceManager.GetString("Z001_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Z001_Language {
            get {
                return ResourceManager.GetString("Z001_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like xtrose.
        /// </summary>
        public static string Z001_Like {
            get {
                return ResourceManager.GetString("Z001_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color list selection.
        /// </summary>
        public static string Z001_ListSelectionColor {
            get {
                return ResourceManager.GetString("Z001_ListSelectionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show logo on start.
        /// </summary>
        public static string Z001_LogoStart {
            get {
                return ResourceManager.GetString("Z001_LogoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player accent color.
        /// </summary>
        public static string Z001_MediaPlayerAccentColor {
            get {
                return ResourceManager.GetString("Z001_MediaPlayerAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu media player.
        /// </summary>
        public static string Z001_MiniPlayer {
            get {
                return ResourceManager.GetString("Z001_MiniPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small media player is installed in the lower menu..
        /// </summary>
        public static string Z001_MiniPlayerTxt {
            get {
                return ResourceManager.GetString("Z001_MiniPlayerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        public static string Z001_Minute {
            get {
                return ResourceManager.GetString("Z001_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Z001_Minutes {
            get {
                return ResourceManager.GetString("Z001_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string Z001_More {
            get {
                return ResourceManager.GetString("Z001_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Z001_Music {
            get {
                return ResourceManager.GetString("Z001_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string Z001_No {
            get {
                return ResourceManager.GetString("Z001_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection can not be played.
        /// </summary>
        public static string Z001_NoteFail {
            get {
                return ResourceManager.GetString("Z001_NoteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, your full version has been released.
        /// </summary>
        public static string Z001_NoteUpdateFullVersion {
            get {
                return ResourceManager.GetString("Z001_NoteUpdateFullVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update available.
        /// </summary>
        public static string Z001_NoUpdateAvailable {
            get {
                return ResourceManager.GetString("Z001_NoUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string Z001_Off {
            get {
                return ResourceManager.GetString("Z001_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Z001_On {
            get {
                return ResourceManager.GetString("Z001_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment please.
        /// </summary>
        public static string Z001_OneMomentPlease {
            get {
                return ResourceManager.GetString("Z001_OneMomentPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other xtrose apps.
        /// </summary>
        public static string Z001_Other {
            get {
                return ResourceManager.GetString("Z001_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Z001_Pause {
            get {
                return ResourceManager.GetString("Z001_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone background.
        /// </summary>
        public static string Z001_PhoneBackground {
            get {
                return ResourceManager.GetString("Z001_PhoneBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string Z001_Playback {
            get {
                return ResourceManager.GetString("Z001_Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last playbacks.
        /// </summary>
        public static string Z001_Playbacks {
            get {
                return ResourceManager.GetString("Z001_Playbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string Z001_Playlist {
            get {
                return ResourceManager.GetString("Z001_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Z001_Playlists {
            get {
                return ResourceManager.GetString("Z001_Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play on.
        /// </summary>
        public static string Z001_PlayOn {
            get {
                return ResourceManager.GetString("Z001_PlayOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play on time.
        /// </summary>
        public static string Z001_PlayOnTime {
            get {
                return ResourceManager.GetString("Z001_PlayOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for purchasing this app.
        /// </summary>
        public static string Z001_PurchaseNote {
            get {
                return ResourceManager.GetString("Z001_PurchaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string Z001_Rate {
            get {
                return ResourceManager.GetString("Z001_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Z001_RateLater {
            get {
                return ResourceManager.GetString("Z001_RateLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Z001_RateNever {
            get {
                return ResourceManager.GetString("Z001_RateNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Z001_RateNow {
            get {
                return ResourceManager.GetString("Z001_RateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application seems to appeal to you.
        ///To program apps is time consuming and difficult.
        ///A good review can help us to spread it further.
        ///
        ///Thank you very much.
        /// </summary>
        public static string Z001_RateText {
            get {
                return ResourceManager.GetString("Z001_RateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore settings.
        /// </summary>
        public static string Z001_RestoreSettings {
            get {
                return ResourceManager.GetString("Z001_RestoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected background.
        /// </summary>
        public static string Z001_SelectedBackground {
            get {
                return ResourceManager.GetString("Z001_SelectedBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected foreground.
        /// </summary>
        public static string Z001_SelectedForeground {
            get {
                return ResourceManager.GetString("Z001_SelectedForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color.
        /// </summary>
        public static string Z001_SetColor {
            get {
                return ResourceManager.GetString("Z001_SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Z001_Settings {
            get {
                return ResourceManager.GetString("Z001_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string Z001_Song {
            get {
                return ResourceManager.GetString("Z001_Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song background.
        /// </summary>
        public static string Z001_SongBackground {
            get {
                return ResourceManager.GetString("Z001_SongBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song foreground.
        /// </summary>
        public static string Z001_SongForeground {
            get {
                return ResourceManager.GetString("Z001_SongForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Z001_Songs {
            get {
                return ResourceManager.GetString("Z001_Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The medium-sized player is opened with a click on the right arrow..
        /// </summary>
        public static string Z001_StandardPlayerTxt {
            get {
                return ResourceManager.GetString("Z001_StandardPlayerTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click screen to skip.
        /// </summary>
        public static string Z001_StartInfo {
            get {
                return ResourceManager.GetString("Z001_StartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Z001_Stop {
            get {
                return ResourceManager.GetString("Z001_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop and remove playback.
        /// </summary>
        public static string Z001_StopPlayback {
            get {
                return ResourceManager.GetString("Z001_StopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback and delete from player.
        /// </summary>
        public static string Z001_StopPlaybackNote {
            get {
                return ResourceManager.GetString("Z001_StopPlaybackNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Z001_Support {
            get {
                return ResourceManager.GetString("Z001_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for downloading.
        /// </summary>
        public static string Z001_ThankYou {
            get {
                return ResourceManager.GetString("Z001_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        public static string Z001_Transparency {
            get {
                return ResourceManager.GetString("Z001_Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired.
        /// </summary>
        public static string Z001_TrialExpired {
            get {
                return ResourceManager.GetString("Z001_TrialExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired! To create apps will cost a lot of time. The price for this work is not expensive. To continue create lock screens Images, you must buy the app. Thank you!.
        /// </summary>
        public static string Z001_TrialNote {
            get {
                return ResourceManager.GetString("Z001_TrialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string Z001_TrialVersion {
            get {
                return ResourceManager.GetString("Z001_TrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        public static string Z001_Warning {
            get {
                return ResourceManager.GetString("Z001_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to white.
        /// </summary>
        public static string Z001_White {
            get {
                return ResourceManager.GetString("Z001_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string Z001_Yes {
            get {
                return ResourceManager.GetString("Z001_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        public static string Z002_NoteLanguage {
            get {
                return ResourceManager.GetString("Z002_NoteLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string Z002_NoteLanguage2 {
            get {
                return ResourceManager.GetString("Z002_NoteLanguage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        public static string Z002_SelectLanguage {
            get {
                return ResourceManager.GetString("Z002_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 Music finally reach your music faster.
        ///The new list view lets you Super fast find your artists, albums or songs.
        ///A mini Player, a small player, and a full-screen player allow to give you full control over your music. In portrait as well as landscape mode.
        ///In addition, there are many extras.
        ///
        ///-List view of your music
        ///-List view of your playlists
        ///-3 different media players
        ///-Supports portrait and landscape
        ///-Short playing the title
        ///-Stop the music and delete from the media player
        ///-100 Last reprod [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZZ000_Beschreibung {
            get {
                return ResourceManager.GetString("ZZ000_Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string ZZ000_Wort1 {
            get {
                return ResourceManager.GetString("ZZ000_Wort1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Mediaplayer.
        /// </summary>
        public static string ZZ000_Wort2 {
            get {
                return ResourceManager.GetString("ZZ000_Wort2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string ZZ000_Wort3 {
            get {
                return ResourceManager.GetString("ZZ000_Wort3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string ZZ000_Wort4 {
            get {
                return ResourceManager.GetString("ZZ000_Wort4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound artist artists song songs album tag albums .
        /// </summary>
        public static string ZZ000_Wort5 {
            get {
                return ResourceManager.GetString("ZZ000_Wort5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press again to close.
        /// </summary>
        public static string ZZ002_AgainClose {
            get {
                return ResourceManager.GetString("ZZ002_AgainClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ZZ002_Apply {
            get {
                return ResourceManager.GetString("ZZ002_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ZZ002_Autor {
            get {
                return ResourceManager.GetString("ZZ002_Autor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string ZZ002_BackgroundColor {
            get {
                return ResourceManager.GetString("ZZ002_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background picture landscape.
        /// </summary>
        public static string ZZ002_BackgroundPictureLandscape {
            get {
                return ResourceManager.GetString("ZZ002_BackgroundPictureLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background picture portrait.
        /// </summary>
        public static string ZZ002_BackgroundPicturePortrait {
            get {
                return ResourceManager.GetString("ZZ002_BackgroundPicturePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ZZ002_Category {
            get {
                return ResourceManager.GetString("ZZ002_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string ZZ002_ColorSelected {
            get {
                return ResourceManager.GetString("ZZ002_ColorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert.
        /// </summary>
        public static string ZZ002_Concert {
            get {
                return ResourceManager.GetString("ZZ002_Concert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting......
        /// </summary>
        public static string ZZ002_ConnectingNow {
            get {
                return ResourceManager.GetString("ZZ002_ConnectingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ZZ002_ConnectionFailed {
            get {
                return ResourceManager.GetString("ZZ002_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with xtrose.
        /// </summary>
        public static string ZZ002_ConnectXtrose {
            get {
                return ResourceManager.GetString("ZZ002_ConnectXtrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string ZZ002_Copy {
            get {
                return ResourceManager.GetString("ZZ002_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ZZ002_Delete {
            get {
                return ResourceManager.GetString("ZZ002_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete picture.
        /// </summary>
        public static string ZZ002_DeletePicture {
            get {
                return ResourceManager.GetString("ZZ002_DeletePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string ZZ002_Design {
            get {
                return ResourceManager.GetString("ZZ002_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designs.
        /// </summary>
        public static string ZZ002_Designs {
            get {
                return ResourceManager.GetString("ZZ002_Designs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out and include images created.
        /// </summary>
        public static string ZZ002_DesignShare_01 {
            get {
                return ResourceManager.GetString("ZZ002_DesignShare_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name:.
        /// </summary>
        public static string ZZ002_DesignShare_02 {
            get {
                return ResourceManager.GetString("ZZ002_DesignShare_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not change.
        /// </summary>
        public static string ZZ002_DesignShare_03 {
            get {
                return ResourceManager.GetString("ZZ002_DesignShare_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add background images from &quot;saved images&quot;.
        /// </summary>
        public static string ZZ002_DesignShare_04 {
            get {
                return ResourceManager.GetString("ZZ002_DesignShare_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how it works.
        ///-Background images are copied into &quot;saved images&quot;
        ///-Point out opens an email to xtrose
        ///-Add author name
        ///-Add images from &quot;saved images&quot;
        ///-Send message
        ///
        ///After a review, we will provide the data on our server.
        ///Thank you very much.
        /// </summary>
        public static string ZZ002_DesignShareNote {
            get {
                return ResourceManager.GetString("ZZ002_DesignShareNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ZZ002_Edit {
            get {
                return ResourceManager.GetString("ZZ002_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR
        ///The foreground color is the same as the background color..
        /// </summary>
        public static string ZZ002_ErrorForeground {
            get {
                return ResourceManager.GetString("ZZ002_ErrorForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR! Name already in use or invalid characters!.
        /// </summary>
        public static string ZZ002_ErrorName {
            get {
                return ResourceManager.GetString("ZZ002_ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color.
        /// </summary>
        public static string ZZ002_ForegroundColor {
            get {
                return ResourceManager.GetString("ZZ002_ForegroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install design......
        /// </summary>
        public static string ZZ002_InstallDesign {
            get {
                return ResourceManager.GetString("ZZ002_InstallDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install design.
        /// </summary>
        public static string ZZ002_InstallNotification {
            get {
                return ResourceManager.GetString("ZZ002_InstallNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons and functions.
        /// </summary>
        public static string ZZ002_InstButtons {
            get {
                return ResourceManager.GetString("ZZ002_InstButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation lock.
        /// </summary>
        public static string ZZ002_InstLock {
            get {
                return ResourceManager.GetString("ZZ002_InstLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next song.
        /// </summary>
        public static string ZZ002_InstNext {
            get {
                return ResourceManager.GetString("ZZ002_InstNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Press) Pause
        ///(Hold) Scan.
        /// </summary>
        public static string ZZ002_InstPause {
            get {
                return ResourceManager.GetString("ZZ002_InstPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ZZ002_InstPlay {
            get {
                return ResourceManager.GetString("ZZ002_InstPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous song.
        /// </summary>
        public static string ZZ002_InstPrevious {
            get {
                return ResourceManager.GetString("ZZ002_InstPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string ZZ002_InstRefresh {
            get {
                return ResourceManager.GetString("ZZ002_InstRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repead.
        /// </summary>
        public static string ZZ002_InstRepead {
            get {
                return ResourceManager.GetString("ZZ002_InstRepead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string ZZ002_InstSearch {
            get {
                return ResourceManager.GetString("ZZ002_InstSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string ZZ002_InstShuffle {
            get {
                return ResourceManager.GetString("ZZ002_InstShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player small accent color.
        /// </summary>
        public static string ZZ002_MediaPlayerAccentColor {
            get {
                return ResourceManager.GetString("ZZ002_MediaPlayerAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player small background color.
        /// </summary>
        public static string ZZ002_MediaPlayerBackgroundColor {
            get {
                return ResourceManager.GetString("ZZ002_MediaPlayerBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player big accent color.
        /// </summary>
        public static string ZZ002_MediaPlayerBigAccentColor {
            get {
                return ResourceManager.GetString("ZZ002_MediaPlayerBigAccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player big background color.
        /// </summary>
        public static string ZZ002_MediaPlayerBigBackgroundColor {
            get {
                return ResourceManager.GetString("ZZ002_MediaPlayerBigBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player picture landscape.
        /// </summary>
        public static string ZZ002_MPBigBackgroundPictureLandscape {
            get {
                return ResourceManager.GetString("ZZ002_MPBigBackgroundPictureLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media player picture portrait.
        /// </summary>
        public static string ZZ002_MPBigBackgroundPicturePortrait {
            get {
                return ResourceManager.GetString("ZZ002_MPBigBackgroundPicturePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ZZ002_Name {
            get {
                return ResourceManager.GetString("ZZ002_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        public static string ZZ002_NewName {
            get {
                return ResourceManager.GetString("ZZ002_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string ZZ002_Notification {
            get {
                return ResourceManager.GetString("ZZ002_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string ZZ002_Online {
            get {
                return ResourceManager.GetString("ZZ002_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string ZZ002_PleaseWait {
            get {
                return ResourceManager.GetString("ZZ002_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string ZZ002_Rename {
            get {
                return ResourceManager.GetString("ZZ002_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore design settings.
        /// </summary>
        public static string ZZ002_ResetColorSettings {
            get {
                return ResourceManager.GetString("ZZ002_ResetColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore settings.
        /// </summary>
        public static string ZZ002_ResetSettings {
            get {
                return ResourceManager.GetString("ZZ002_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string ZZ002_Restore {
            get {
                return ResourceManager.GetString("ZZ002_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ZZ002_Save {
            get {
                return ResourceManager.GetString("ZZ002_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Background.
        /// </summary>
        public static string ZZ002_SelectedBackground {
            get {
                return ResourceManager.GetString("ZZ002_SelectedBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Foreground.
        /// </summary>
        public static string ZZ002_SelectedForeground {
            get {
                return ResourceManager.GetString("ZZ002_SelectedForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string ZZ002_Share {
            get {
                return ResourceManager.GetString("ZZ002_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background black.
        /// </summary>
        public static string ZZ002_StandardBlack {
            get {
                return ResourceManager.GetString("ZZ002_StandardBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background white.
        /// </summary>
        public static string ZZ002_StandardWhite {
            get {
                return ResourceManager.GetString("ZZ002_StandardWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time out.
        /// </summary>
        public static string ZZ002_TimeOut {
            get {
                return ResourceManager.GetString("ZZ002_TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Version Expired! To create apps will cost a lot of time. The price for this work is not expensive. To continue to use this app, you have to buy it. Thank you!.
        /// </summary>
        public static string ZZ002_TrialNote {
            get {
                return ResourceManager.GetString("ZZ002_TrialNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose unsaved design settings.
        /// </summary>
        public static string ZZ002_WarningApplyDesign {
            get {
                return ResourceManager.GetString("ZZ002_WarningApplyDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 music finally reach your music faster.
        ///The new list view lets you Super fast find your artists, albums or songs.
        ///A mini Player, a small player, and a full-screen player allow to give you full control over your music. In portrait as well as landscape mode.
        ///Create your own design or download finished designs from the Internet.
        ///In addition, there are many extras.
        ///
        ///-List view of your music
        ///-List view of your playlists
        ///-3 different media players
        ///-Supports portrait and landscape
        ///-Short playing the t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZZ002_ZZ_BeschreibungNeu {
            get {
                return ResourceManager.GetString("ZZ002_ZZ_BeschreibungNeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background picture.
        /// </summary>
        public static string ZZ003_BackgroundPicture {
            get {
                return ResourceManager.GetString("ZZ003_BackgroundPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press twice again to renew cache.
        /// </summary>
        public static string ZZ003_ClickClearCatch {
            get {
                return ResourceManager.GetString("ZZ003_ClickClearCatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press again to renew catch.
        /// </summary>
        public static string ZZ003_ClickClearCatch2 {
            get {
                return ResourceManager.GetString("ZZ003_ClickClearCatch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to create stop and delete tile.
        /// </summary>
        public static string ZZ003_CreateTileNote {
            get {
                return ResourceManager.GetString("ZZ003_CreateTileNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number 0 - 360.
        /// </summary>
        public static string ZZ003_ErrorRunUnder {
            get {
                return ResourceManager.GetString("ZZ003_ErrorRunUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo on the album image.
        /// </summary>
        public static string ZZ003_LogoAlbumImage {
            get {
                return ResourceManager.GetString("ZZ003_LogoAlbumImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main tile.
        /// </summary>
        public static string ZZ003_MainTile {
            get {
                return ResourceManager.GetString("ZZ003_MainTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - 360 Minutes.
        /// </summary>
        public static string ZZ003_Minutes {
            get {
                return ResourceManager.GetString("ZZ003_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update list
        ///Double click on notification to recreate list. Only necessary if changed music on your mobile..
        /// </summary>
        public static string ZZ003_Refresh {
            get {
                return ResourceManager.GetString("ZZ003_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ZZ003_Reset {
            get {
                return ResourceManager.GetString("ZZ003_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset main tile.
        /// </summary>
        public static string ZZ003_ResetMainTile {
            get {
                return ResourceManager.GetString("ZZ003_ResetMainTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run under lock screen.
        /// </summary>
        public static string ZZ003_RunUnderLockScreen {
            get {
                return ResourceManager.GetString("ZZ003_RunUnderLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start screen settings.
        /// </summary>
        public static string ZZ003_StartMenüSettings {
            get {
                return ResourceManager.GetString("ZZ003_StartMenüSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start screen.
        /// </summary>
        public static string ZZ003_StartScreen {
            get {
                return ResourceManager.GetString("ZZ003_StartScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile stop and delete.
        /// </summary>
        public static string ZZ003_StopDeleteTile {
            get {
                return ResourceManager.GetString("ZZ003_StopDeleteTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop timer.
        /// </summary>
        public static string ZZ003_StopTimer {
            get {
                return ResourceManager.GetString("ZZ003_StopTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the timer the app must be running under the lock screen.
        ///Enable to run under the lock screen.
        /// </summary>
        public static string ZZ003_TimerRunNote {
            get {
                return ResourceManager.GetString("ZZ003_TimerRunNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.1 music finally reach your music faster.
        ///The new list view lets you Super fast find your artists, albums or songs.
        ///A mini Player, a small player, and a full-screen player allow to give you full control over your music. In portrait as well as landscape mode.
        ///Create your own design or download finished designs from the Internet.
        ///In addition, there are many extras.
        ///
        ///-List view of your music
        ///-List view of your playlists
        ///-3 different media players
        ///-Supports portrait and landscape
        ///-Short playing the t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZZ003_ZZ_Beschreibung {
            get {
                return ResourceManager.GetString("ZZ003_ZZ_Beschreibung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press twice again to renew cache.
        /// </summary>
        public static string ZZ004_ClickClearCache {
            get {
                return ResourceManager.GetString("ZZ004_ClickClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew.
        /// </summary>
        public static string ZZ004_Renew {
            get {
                return ResourceManager.GetString("ZZ004_Renew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew cache.
        /// </summary>
        public static string ZZ004_RenewCache {
            get {
                return ResourceManager.GetString("ZZ004_RenewCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic translation.
        /// </summary>
        public static string ZZ005_AutoTranslate {
            get {
                return ResourceManager.GetString("ZZ005_AutoTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons media player.
        /// </summary>
        public static string ZZ005_ButtonsMediaPlayer {
            get {
                return ResourceManager.GetString("ZZ005_ButtonsMediaPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons of the list.
        /// </summary>
        public static string ZZ005_ButtonsOfList {
            get {
                return ResourceManager.GetString("ZZ005_ButtonsOfList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache system.
        /// </summary>
        public static string ZZ005_CacheSystem {
            get {
                return ResourceManager.GetString("ZZ005_CacheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first load of the content needs some time. Then load the contents from a cache. If you add new content to your device you must refresh the cache.
        ///You can refresh the cache in the settings..
        /// </summary>
        public static string ZZ005_CacheSystemTxt {
            get {
                return ResourceManager.GetString("ZZ005_CacheSystemTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear current playlist.
        /// </summary>
        public static string ZZ005_ClearCurrent {
            get {
                return ResourceManager.GetString("ZZ005_ClearCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the logo to open the help.
        /// </summary>
        public static string ZZ005_ClickLogoToHelp {
            get {
                return ResourceManager.GetString("ZZ005_ClickLogoToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current playlist.
        /// </summary>
        public static string ZZ005_CurrentPlaylist {
            get {
                return ResourceManager.GetString("ZZ005_CurrentPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete current playback.
        /// </summary>
        public static string ZZ005_DeletePlayback {
            get {
                return ResourceManager.GetString("ZZ005_DeletePlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete playlist.
        /// </summary>
        public static string ZZ005_DeletePlaylist {
            get {
                return ResourceManager.GetString("ZZ005_DeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete playlist.
        /// </summary>
        public static string ZZ005_DeletePlaylist2 {
            get {
                return ResourceManager.GetString("ZZ005_DeletePlaylist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design error!
        ///Delete the design and download it again to fix this error..
        /// </summary>
        public static string ZZ005_DesignError {
            get {
                return ResourceManager.GetString("ZZ005_DesignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display problems.
        /// </summary>
        public static string ZZ005_DisplayProblems {
            get {
                return ResourceManager.GetString("ZZ005_DisplayProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many songs can cause problems with the display. The problems associated with the transparent color of the designs.
        ///You can fix the problem if you remove the transparency of the designs..
        /// </summary>
        public static string ZZ005_DisplayProblemsTxt {
            get {
                return ResourceManager.GetString("ZZ005_DisplayProblemsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read!
        ///Welcome to the new version 8.1 music.
        ///To help you get started, we have created a new help. Press the logo above to open help.
        ///Starting with this release, there is a completely new mode.
        ///Please note the new mode, &quot;select and play&quot; is still in the testing phase.
        ///Give us please know if you find an error.
        ///Thank you very much!
        ///
        ///Have fun with the new version.
        /// </summary>
        public static string ZZ005_FirstNote {
            get {
                return ResourceManager.GetString("ZZ005_FirstNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create playlist.
        /// </summary>
        public static string ZZ005_HelpCreatePlaylist {
            get {
                return ResourceManager.GetString("ZZ005_HelpCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists can only in the &quot; select and play&quot; mode will be created.
        ///- Activate &quot;Select and Play&quot;
        ///- Go to the current playback and delete them
        ///- Select from the list your music
        ///- Go to the current playback and press save
        ///- Enter a name for your new playlist
        ///- You will find your new playlist in the second list under playlists.
        /// </summary>
        public static string ZZ005_HelpCreatePlaylistTxt {
            get {
                return ResourceManager.GetString("ZZ005_HelpCreatePlaylistTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This button deletes the current playback and unselect all songs in the lists..
        /// </summary>
        public static string ZZ005_HelpDelete {
            get {
                return ResourceManager.GetString("ZZ005_HelpDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string ZZ005_HelpHeader {
            get {
                return ResourceManager.GetString("ZZ005_HelpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this button to lock the orientation.
        ///It will be blocked always the current orientation.
        ///Press the button again to unlock it..
        /// </summary>
        public static string ZZ005_HelpOrientationLock {
            get {
                return ResourceManager.GetString("ZZ005_HelpOrientationLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this button, the lists are closed and renewed.
        ///By double-clicking on the published notice, the cache is updated.
        ///The cache must be renewed only if the music of the Smartphone has been changed..
        /// </summary>
        public static string ZZ005_HelpRefresh {
            get {
                return ResourceManager.GetString("ZZ005_HelpRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this button, the current playback as a playlist can be saved. Available only in mode, select and play..
        /// </summary>
        public static string ZZ005_HelpSave {
            get {
                return ResourceManager.GetString("ZZ005_HelpSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One press on the search, then opens a text input.
        ///Enter your search term and press return.
        ///The search filters all lists.
        ///Use close and renew lists to delete the search..
        /// </summary>
        public static string ZZ005_HelpSearch {
            get {
                return ResourceManager.GetString("ZZ005_HelpSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design editor.
        /// </summary>
        public static string ZZ005_InstDesignEditor {
            get {
                return ResourceManager.GetString("ZZ005_InstDesignEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost everything can be adjusted in this app.
        ///Background images, background colors, foreground color, the individual colors of the list.
        ///To change the color settings, you need to open the design.
        ///Here, you can make the app to your liking.
        ///
        ///You can download complete themes and install directly.
        ///
        ///With the share button you can send us your design.
        ///Please remember to add the generated images.
        ///We will like to upload your design..
        /// </summary>
        public static string ZZ005_InstDesignEditorTxt {
            get {
                return ResourceManager.GetString("ZZ005_InstDesignEditorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design error.
        /// </summary>
        public static string ZZ005_InstDesignError {
            get {
                return ResourceManager.GetString("ZZ005_InstDesignError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the download of design errors can occur.
        ///In the select the themes the app crashes.
        ///The design is reset at the next startup.
        ///To use the design, it must be installed again..
        /// </summary>
        public static string ZZ005_InstDesignErrorTxt {
            get {
                return ResourceManager.GetString("ZZ005_InstDesignErrorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loaded.
        /// </summary>
        public static string ZZ005_loaded {
            get {
                return ResourceManager.GetString("ZZ005_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select playlist.
        /// </summary>
        public static string ZZ005_LoadPlaylist {
            get {
                return ResourceManager.GetString("ZZ005_LoadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No songs in the current replay available.
        /// </summary>
        public static string ZZ005_NoSongsAvailable {
            get {
                return ResourceManager.GetString("ZZ005_NoSongsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string ZZ005_Overview {
            get {
                return ResourceManager.GetString("ZZ005_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ZZ005_Play {
            get {
                return ResourceManager.GetString("ZZ005_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A playlist with the same name already exists.
        ///
        ///Override playlist.
        /// </summary>
        public static string ZZ005_PlaylistAvailable {
            get {
                return ResourceManager.GetString("ZZ005_PlaylistAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play only this title.
        /// </summary>
        public static string ZZ005_PlayOnly {
            get {
                return ResourceManager.GetString("ZZ005_PlayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist.
        /// </summary>
        public static string ZZ005_SavePlaylist {
            get {
                return ResourceManager.GetString("ZZ005_SavePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the mode select and play the playlist can be saved.
        ///This button appears in the field of the current playback.
        ///Clicking the button opens a text input field.
        ///After a name has been entered here you have to press the return button.
        ///Point out the playlist in a playlist is saved.
        ///You can find them in the second list..
        /// </summary>
        public static string ZZ005_SavePlaylistText {
            get {
                return ResourceManager.GetString("ZZ005_SavePlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and play
        ///This button changes the mode of the app.
        ///
        ///Standard mode
        ///In the default mode the app use the specified API.
        ///Advantages
        ///- The app can be closed after the selection.
        ///- The music can be controlled by the system.
        ///Disadvantages
        ///- It can be played only what the API allowing. No own mixes can be created.
        ///- There are no playlists that can be created.
        ///- Now playing can not be changed.
        ///
        ///Select and play mode
        ///In this mode, everything can be selected and played back directly.
        ///Advantages
        ///-  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZZ005_SelectAndPlay {
            get {
                return ResourceManager.GetString("ZZ005_SelectAndPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and play.
        /// </summary>
        public static string ZZ005_SelectAndPlayHeader {
            get {
                return ResourceManager.GetString("ZZ005_SelectAndPlayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and play mode.
        /// </summary>
        public static string ZZ005_SelectAndPlayMode {
            get {
                return ResourceManager.GetString("ZZ005_SelectAndPlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or deselect.
        /// </summary>
        public static string ZZ005_SelectDeselect {
            get {
                return ResourceManager.GetString("ZZ005_SelectDeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard mode.
        /// </summary>
        public static string ZZ005_StandardMode {
            get {
                return ResourceManager.GetString("ZZ005_StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top button bar.
        /// </summary>
        public static string ZZ005_TopBar {
            get {
                return ResourceManager.GetString("ZZ005_TopBar", resourceCulture);
            }
        }
    }
}
